version: 3

silent: true

vars:
  NENV: "node_modules"

tasks:
  _prettier:
    internal: true
    cmds:
      - "{{.NENV}}/.bin/prettier {{.COMMAND}}"

  _eslint:
    internal: true
    cmds:
      - "{{.NENV}}/.bin/eslint {{.COMMAND}}"

  _with_nvm:
    internal: true
    cmds:
      - "source ${HOME}/.nvm/nvm.sh && nvm install && {{.COMMAND}}"

  init:
    desc: Initialize project environment
    cmds:
      - echo 'Installing node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm install" }

      - echo 'Installing husky pre-commit...'
      - task: _with_nvm
        vars: { COMMAND: "npm run prepare" }

  lint:
    desc: Lint project
    cmds:
      - echo 'Running prettier checks...'
      - task: _prettier
        vars: { COMMAND: "--check ." }

      - echo 'Running eslint checks...'
      - task: _eslint
        vars: { COMMAND: "." }

  lint-fix:
    desc: Lint fix project
    cmds:
      - echo 'Running prettier fixes...'
      - task: _prettier
        vars: { COMMAND: "--write ." }

      - echo 'Running eslint fixes...'
      - task: _eslint
        vars: { COMMAND: "--fix ." }

  test:
    desc: Test project
    cmds:
      - echo 'Running tests...'

  clean:
    desc: Clean project environment
    cmds:
      - echo 'Cleaning node dependencies...'
      - rm -rf {{.NENV}}

  dev-server-start:
    desc: Start development server
    cmds:
      - echo 'Starting development server...'
      - task: _with_nvm
        vars: { COMMAND: "npm run dev" }

  dist-build:
    desc: Build project distribution
    cmds:
      - echo 'Building project distribution...'
      - task: _with_nvm
        vars: { COMMAND: "npm run build" }

  dist-preview:
    desc: Preview project distribution
    cmds:
      - echo 'Previewing project distribution...'
      - task: _with_nvm
        vars: { COMMAND: "npm run preview" }

  dependencies-update:
    desc: Update dependencies
    cmds:
      - echo 'Updating node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm update" }
      - task: _with_nvm
        vars: { COMMAND: "npm outdated" }
      - task: _with_nvm
        vars: { COMMAND: "npm audit" }

  update-from-template:
    desc: Update project from template
    cmds:
      - echo 'Updating project from template...'
      - cookiecutter
        --no-input
        --overwrite-if-exists
        --output-dir ../
        {{.TEMPLATE_PATH}}
        project_name="DnD Card Printer"
        project_slug="dnd-card-printer"
        node_version="v20.15.1"
        github_owner="ovsds"
    vars:
      TEMPLATE_PATH: '{{.TEMPLATE_PATH | default "https://github.com/ovsds/template-repository"}}'
